  GNU nano 6.2                                                                                                                        Makefile                                                                                                                           M
TARGET := chr_dev
$(TARGET)-objs := main.o chr_dev.o
obj-m += $(TARGET).o

all:
        make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules

clean:
        make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
load:
        insmod ./$(TARGET).ko
unload:
        rmmod ./$(TARGET).ko

